name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

 # sleep
  sleeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sleep 5
  test:
   runs-on: ubuntu-latest
   needs: sleeps
   steps:
   - uses: actions/checkout@v1
   - uses: ./
     with:
       myToken: ${{ secrets.GITHUB_TOKEN }} 
