name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
   

 # tests 30sec sleep
  sleeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sleep 30
    - uses: ./

  # test no sleep 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./

  depjob:
    runs-on: ubuntu-latest
    needs: [sleeps, test]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
