name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

 # sleep
  sleeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sleep 5
    - uses: ./
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
